from predictor.Predictor import Predictor
from predictor.ancient_chinese_predictor import AncientChinesePredictor
from predictor.test_predictor import TestPredictor
from predictor.recognizion_predictor.recognize_predictor import Recognize_Predictor_batch




